### ISSUE TITLE
Disable stackable toasts

### ISSUE THREAD

**Issue by Icaras12x** [apvarun/toastify-js#43]
What about an option to disable the way toasts stack one on another and let them always be generated one on top of eachother, occupying only one space ?

**Comment by apvarun** [comment]
@Icaras12x Since its a very specific use case, I believe that this can be achieved in your custom code by manually hiding the previous toast and showing the new one. 
**Sample:** https://codesandbox.io/s/toastify-multiple-toasts-dwd4p

Few other reasons that I think this shouldn't be included in the library:
- Keeping the lib small by not polluting it with indirect requirements
- Since we have a default drop shadow on the element, stacking it isn't gonna give a nice user experience, and so it might need style tweaking as well.
